### ISSUE TITLE
validar cis de 6 dígitos xxx.xxx-x en validador .py

### ISSUE THREAD

**Issue by upadrian** [upadrian/uruguay-ci-checker#1]
Revisar el validador py, ver que valide ci's de 6 dígitos, como xxx.xxx-x

**Comment by ivanhalencp** [comment]
Resuelto. Ahora se aceptan cis con puntos y guiones también.

**Comment by upadrian** [comment]
El tema es que por lo que vi, si te mando una ci 829.358-7 (por decir algo, no es correcta), creo que no la valida.
Recordá que la ci sin digito verificador puede ser 6 o  7 dígitos, y con digito son 7 u 8.
No tengo para probar ak, fijate vos
